### ISSUE TITLE
Попробуй TextChoices. Понравится :)

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#1]
https://github.com/BPIlyich/insu-bro-nce/blob/873253b24bb1309baddec8ac719901266c5651df/insu-bro-nce/insurance/models.py#L32

Попробуй TextChoices. Понравится :)

https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

**Comment by BPIlyich** [comment]
Учтем!

**Comment by BPIlyich** [comment]
> https://github.com/BPIlyich/insu-bro-nce/blob/873253b24bb1309baddec8ac719901266c5651df/insu-bro-nce/insurance/models.py#L32
> 
> Попробуй TextChoices. Понравится :)
> 
> https://docs.djangoproject.com/en/3.2/ref/models/fields/#enumeration-types

Учту.
