### ISSUE TITLE
Отлично. Фикстуры сильно улучшают тестирование.

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#13]
https://github.com/BPIlyich/insu-bro-nce/blob/089413a809343e1626a26260908d4cbd878ebedb/fixtures.json#L1

**Comment by BPIlyich** [comment]
@programishka, как лучше делать фикстуры? Одним файлом как у меня сейчас или на каждое приложение свой файл с фикстурами?

**Comment by programishka** [comment]
Думаю разницы нет.
Есть только разница в том, если консистентность проекта может быть разрушена, таким образом у приложений сильная связанность, то только один вариант. Общая фикстура на проект.
