### ISSUE TITLE
Сообщения об откликах не отправились.

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#14]
https://github.com/BPIlyich/insu-bro-nce/blob/089413a809343e1626a26260908d4cbd878ebedb/insu-bro-nce/insurance/views.py#L123

Сообщения не отправились. Я не работал с библиотекой anymail. Возможно проблема в настройках.

**Comment by BPIlyich** [comment]
> https://github.com/BPIlyich/insu-bro-nce/blob/089413a809343e1626a26260908d4cbd878ebedb/insu-bro-nce/insurance/views.py#L123
> 
> Сообщения не отправились. Я не работал с библиотекой anymail. Возможно проблема в настройках.

@programishka, Вы заполнили `SENDINBLUE_API_KEY` в файле `dev.env`?
Чтобы получить `SENDINBLUE_API_KEY` нужно зарегистрироваться на https://www.sendinblue.com/
Размещать свой `SENDINBLUE_API_KEY` в открытом репозитории считаю не лучшим решением.

Также напомню, что оповещение уходит на почту компании, разместившей страховой продукт. У всех компаний из фикстур несуществующие почты. 
Чтобы протестировать данный функционал следует зарегистрироваться с почтой к которой у Вас есть доступ. Создать страховой продукт и после оставить на него отклик.

**Comment by programishka** [comment]
Согласен.
Считаю что в README.MD стоит добавить эту информацию :)

**Comment by BPIlyich** [comment]
> Согласен.
> Считаю что в README.MD стоит добавить эту информацию :)

А она там есть :)
https://github.com/BPIlyich/insu-bro-nce/blob/main/README.md#%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-email-%D1%80%D0%B0%D1%81%D1%81%D1%8B%D0%BB%D0%BE%D0%BA

**Comment by programishka** [comment]
Эх. А слона то я и не заметил :)

**Comment by BPIlyich** [comment]
done
