### ISSUE TITLE
Невозможно создать нового супер админа из консоли

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#3]
https://github.com/BPIlyich/insu-bro-nce/blob/873253b24bb1309baddec8ac719901266c5651df/insu-bro-nce/users/models.py#L18

Невозможно создать нового супер админа из консоли. так как не запрашивается email, а email не указан при создании.

**Comment by BPIlyich** [comment]
> https://github.com/BPIlyich/insu-bro-nce/blob/873253b24bb1309baddec8ac719901266c5651df/insu-bro-nce/users/models.py#L18
> 
> Невозможно создать нового супер админа из консоли. так как не запрашивается email, а email не указан при создании.

Учту
