### ISSUE TITLE
Очень круто что используешь перевод. Но если переводить, желательно переводить всё

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#4]
https://github.com/BPIlyich/insu-bro-nce/blob/873253b24bb1309baddec8ac719901266c5651df/insu-bro-nce/insurance/locale/ru/LC_MESSAGES/django.po#L9

**Comment by programishka** [comment]
Очень круто что используешь перевод. Но если переводить, желательно переводить всё http://0.0.0.0:8080/insurance/product/response/table/ Например тут кннопки и заголовок не переведены.

**Comment by BPIlyich** [comment]
> Очень круто что используешь перевод. Но если переводить, желательно переводить всё http://0.0.0.0:8080/insurance/product/response/table/ Например тут кннопки и заголовок не переведены.

Перевод почти готов. Скорее всего будет в следующем коммите.
