### ISSUE TITLE
Восстановление пароля можно делать через очередь. Это хорошо.

### ISSUE THREAD

**Issue by programishka** [BPIlyich/insu-bro-nce#9]
https://github.com/BPIlyich/insu-bro-nce/blob/fd6dc90c55b47598838242c6285e7b5e93071c58/insu-bro-nce/users/urls.py#L32

- Сейчас в приложении рассылка уведомлений об откликах на страховые продукты реализована через очередь (celery + RabbitMQ). Стоит ли делать отправку письма на восстановление пароля через очередь? Есть ли какие-то "подводные камни" из-за которых так делать не стоит?

**Comment by BPIlyich** [comment]
Сделано
https://github.com/BPIlyich/insu-bro-nce/commit/e5ac91e8a5f47b6f90d1779f702018f542bebf73
